language: python
python: "3.6"
script: npm run build
after_success:
- git remote set-url origin git@github.com:CryptoCatalog/ultimate-crypto-comparison.git
- openssl aes-256-cbc -K $encrypted_e7cc94ff2647_key -iv $encrypted_e7cc94ff2647_iv -in ./lib/travis/github_deploy_key.enc -out id_rsa -d
- ssh-add github_deploy_key
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
- git reset --hard
- echo $TRAVIS_BRANCH
- echo $TRAVIS_PULL_REQUEST
- ./lib/travis/deploy.sh
before_install:
- nvm install 6
- node --version
- npm install -g npm
- java -version
- npm -version
install:
- pip install -r ./lib/gitScrabber/git-scrabber-packages.txt
sudo: required
dist: trusty
