language: node_js
node_js:
- '6'
env:
- GIT_DEPLOY_DIR: www
script: npm run build
after_success:
- git remote set-url origin git@github.com:ultimate-comparisons/ultimate-comparison-BASE.git
#- openssl aes-256-cbc -K $encrypted_08460152d0a3_key -iv $encrypted_08460152d0a3_iv -in id_rsa.enc -out id_rsa -d
- openssl aes-256-cbc -K $encrypted_e7cc94ff2647_key -iv $encrypted_e7cc94ff2647_iv -in github_deploy_key.enc -out id_rsa -d
- ssh-add github_deploy_key
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
- git reset --hard
- echo $TRAVIS_BRANCH
- echo $TRAVIS_PULL_REQUEST
- ./deploy.sh
before_install:
- npm install -g npm
- java -version
- npm -version
sudo: required
dist: trusty
