language: python
python:
  - "3.6"
script: travis_wait 60 npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
before_install:
- npm install -g npm
- npm install gulp
- java -version
- npm -version
install:
- pip install -r ./lib/gitScrabber/git-scrabber-packages.txt
sudo: required
dist: trusty
